services:
  db:
    image: mysql:8
    container_name: de_roemah_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "deroemah"
      MYSQL_USER: "user"
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
